### ISSUE TITLE
Moving from stable 3033.2.4 to 3139.2.0 made kitchen tests fail

### ISSUE THREAD

**Issue by obourdon** [flatcar/Flatcar#733]
## Description

The following code now fails changing 3033.2.4 into 3139.2.0:

```
# test/integration/default/controls/operating_system_spec.rb
control 'operating_system' do
  describe command('grep PRETTY_NAME /etc/os-release') do
    its('stdout') { should match (/Flatcar Container Linux by Kinvolk/) }
  end

  describe command('grep VERSION= /etc/os-release') do
    its('stdout') { should match (/3033.2.4/) }
  end

  describe os.name do
    it { should eq 'coreos' }
  end

  describe os.release do
    it { should eq '3033.2.4' }
  end
end
```

## Impact

Can not deliver automatically new images based on 3139.2.9 via CI

## Environment and steps to reproduce

AWS based images produced from official Flatcar AMIs

## Expected behavior

Formerly the output of the tests gave:
```
  ✔  operating_system: Command: `grep PRETTY_NAME /etc/os-release`
     ✔  Command: `grep PRETTY_NAME /etc/os-release` stdout is expected to match /Flatcar Container Linux by Kinvolk/
     ✔  Command: `grep VERSION= /etc/os-release` stdout is expected to match /3033.2.4/
     ✔  coreos is expected to eq "coreos"
     ✔  3033.2.4 is expected to eq "3033.2.4"
```

and now:
```
  ×  operating_system: Command: `grep PRETTY_NAME /etc/os-release` (2 failed)
     ✔  Command: `grep PRETTY_NAME /etc/os-release` stdout is expected to match /Flatcar Container Linux by Kinvolk/
     ✔  Command: `grep VERSION= /etc/os-release` stdout is expected to match /3139.2.0/
     ×  linux is expected to eq "coreos"
     
     expected: "coreos"
          got: "linux"
     
     (compared using ==)

     ×  unknown is expected to eq "3139.2.0"
     
     expected: "3139.2.0"
          got: "unknown"
     
     (compared using ==)
```

## Additional informations

kitchen tests are run in CI via a Docker container based on ruby:2.7-alpine3.13 and Terraform 0.12.31 to deploy images on AWS

I'll try to extract minimum set of elements to help reproduce this case more easily

Tried several versions of ruby gems (up to latest available) without more success

Again this IS PERFECTLY working without any other change than the Flatcar stable version

**Comment by jepio** [comment]
Where is the code for whatever `os.name` or `os.release` are? Does this have any connection to ansible? Can you test if creating `/etc/flatcar/update.conf` (empty) changes anything?

**Comment by obourdon** [comment]
@jepio, many thanks for answering.

 AFAIK the corresponding code lies within the [inspec](https://docs.chef.io/inspec/resources/os/) Ruby Gem of kitchen tests 
See [https://kitchen.ci/](https://kitchen.ci/ )for more infos on Kitchen tests

I am currently testing with an empty file as suggested (I also just checked that there is no such file, not even empty, in the original image) and will let you know the outcome ASAP

**Comment by obourdon** [comment]
@jepio it definitely works with an empty file. Even though I find this very strange I really appreciate you taking the time and pointing me in the right direction.
As I do not have any leverage on how the AWS base images are produced do you think this issue should be fixed more
generically and therefore I leave it open or do you have any other suggestion.
Many thanks again

**Comment by jepio** [comment]
Ok, thanks. I asked about ansible, because we found that ansible was accidentally relying on the existence of that file for determining os facts (https://github.com/flatcar-linux/Flatcar/issues/719). I still can't find where in the inspec code this detection happens.

Let's leave this open because we still need to figure out what to do about this. cc: @pothos

**Comment by pothos** [comment]
We talked about always creating the file, I've filed a PR for that: https://github.com/flatcar-linux/init/pull/71

**Comment by pothos** [comment]
The fix is merged and I'll close this now even though it will be out only in the next round of releases

**Comment by pothos** [comment]
FYI: A bug report to the project would be good because testing for `/etc/flatcar/update.conf` is not the best idea as we've seen now. Also, in the case of Flatcar there is a `/etc/coreos/update.conf` file through the `/etc/coreos → /etc/flatcar` directory symlink, so Flatcar could have been mistaken for CoreOS depending on the order of the check and a future OS that wants to be compatible and provide `/etc/flatcar/update.conf` would end up being detected as Flatcar which may not be wanted.
The only sane solution out of this is to use the `/etc/os-release` file's ID field.

**Comment by obourdon** [comment]
@pothos I fully understand and agree, I'll dig deeper into this whenever times permit however I am definitely not an expert in kitchen/inspec/... source code investigations but I'll see what I can come up with
